  name: First workflow
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Hello
          run: echo "Hello!!! from ${{github.workflow }} triggered byt the ${{github.event_name}}"