  name: First workflow
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Hello
          run: echo "Hello!!! from ${{github.workflow }} triggered byt the ${{github.event_name}}"
        - name: other step
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: |
            echo "job context: $JOB_CONTEXT"
            echo "Done"
